account/urls.py
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login, name='login'),
    path('signup/', views.signup, name='signup'),
    path('logout/', views.logout, name='logout'),
    path('about/', views.about, name='about'),
    path('err/', views.err404disp, name='err404'),

]

app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('<int:app_id>/', views.showproject, name='show'),
    path('prev_snap/<int:app_id>/', views.loadDataNext, name='prev_snap'),
    path('next_snap/<int:app_id>/', views.loadDataNext, name='next_snap'),
    path('like/<int:app_id>/', views.make_like,name='make_like'),
    path('create/', views.createProject, name='create'),
    path('addsnap/<int:app_id>/', views.addSnap, name='add_snap'),
    path('delete/<int:app_id>/', views.deleteSnap, name='delete_snap'),
    path('editsnap/<int:app_id>/', views.editSnap, name='edit_snap'),
    path('delete_project/<int:app_id>/', views.deleteProject, name='delete_project'),
    path('delete_stack/', views.deleteStack, name='delete_stack'),
    path('add_stack/<int:app_id>/', views.addStack, name='add_stack'),


]

cabinet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import account.urls
import app.urls
import account

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(account.urls)),
    path('show/', include(app.urls))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'account.views.err404'
# handler500 = 'account.views.500'
# handler403 = 'account.views.403'
# handler400 = 'account.views.400'

cabinet/templates/components/footer.html
{% load static %}
<div class="custom-footer ">
    <div class="row mx-0">
        <div class="branding col-lg-4 col-md-4 col-sm-12">
          <div style="display: flex;flex-direction: column;">
                  <img style="margin-right: 10px;width:50%;
                          height: 50%" src="{% static 'images/cablogo.png' %}">
              </div>
            <div>
                <p>Showcase your Masterpiece</p><br>
            </div>
        </div>
        <div class="footer-items col-lg-4 col-md-4 col-sm-12">
            <ul class="footer-items-list">
                <li>Contact</li>
                <li><a>+91-9010778702</a></li>
                <li><a>syntaxerrorinline1@gmail.com</a></li>
                <li><a href="#">Facebook page</a></li>
            </ul>
        </div>

        <div class="footer-items col-lg-4 col-md-4 col-sm-12">
            <ul class="footer-items-list">
                <li>Company</li>
                <li><a href="{% url 'account:about' %}">About Us</a></li>
                <li><a href="{% url 'account:err404' %}">Privacy Policy</a></li>
                <li><a href="#">Copyright Policy</a></li>
            </ul>
        </div>

    </div>
</div>

cabinet/templates/components/header.html
{% load static %}
<nav style="background-color: rgba(0, 0, 0, 0.1);" class="navbar navbar-expand-lg fixed-top navbar-light ">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'account:home' %}">
              <div class="navbar-title">
                  <img src="{% static 'images/cabicon.png' %}"  style="margin-right: 10px" height="36" class="d-inline-block align-top" alt="">
                  Cabinet.
                </div>
          </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
            <ul class="navbar-nav mr-auto">
              {% if user.is_authenticated %}
              <form id="gohome" action="{% url 'account:home' %}">
                   <input type="hidden" />
              </form>
              <li class="nav-item">
                  <div class="header-buttons" onclick="javascript:{document.getElementById('gohome').submit()}">
                      <h3 class="header-buttons-text">MY PROJECTS</h3>
                  </div>
              </li>
              <li class="nav-item">
                  <div class="header-buttons header-buttons-other" onclick="javascript:{document.getElementById('logout').submit()}">
                      <h3 class="header-buttons-text">LOGOUT</h3>
                  </div>
              </li>
  <form id="logout" method="POST" action="{% url 'account:logout' %}">
       {% csrf_token %}
       <input type="hidden" />
  </form>
  {% else %}
  <form id="login" action="{% url 'account:login' %}">
       <input type="hidden" />
  </form>
  <form id="signup" action="{% url 'account:signup' %}">
       <input type="hidden" />
  </form>
  <li class="nav-item">
      <div class="header-buttons" onclick="javascript:{document.getElementById('login').submit()}">
          <h3 class="header-buttons-text">LOGIN</h3>
      </div>
  </li>
  <li class="nav-item">
      <div class="header-buttons header-buttons-other" onclick="javascript:{document.getElementById('signup').submit()}">
          <h3 class="header-buttons-text">SIGNUP</h3>
      </div>
  </li>
  {% endif %}

            </ul>
        </div>
    </div>
</nav>