app/urls.py
from django.urls import path
from app import views

app_name = 'app'

urlpatterns = [
    path('<int:app_id>/', views.showproject, name='show'),
    path('prev_snap/<int:app_id>/', views.loadDataNext, name='prev_snap'),
    path('next_snap/<int:app_id>/', views.loadDataNext, name='next_snap'),
    path('like/<int:app_id>/', views.make_like,name='make_like'),
    path('create/', views.createProject, name='create'),
    path('addsnap/<int:app_id>/', views.addSnap, name='add_snap'),
    path('delete/<int:app_id>/', views.deleteSnap, name='delete_snap'),
    path('editsnap/<int:app_id>/', views.editSnap, name='edit_snap'),
    path('delete_project/<int:app_id>/', views.deleteProject, name='delete_project'),
    path('delete_stack/', views.deleteStack, name='delete_stack'),
    path('add_stack/<int:app_id>/', views.addStack, name='add_stack'),


]

cabinet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
import account.urls
import app.urls
import account

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(account.urls)),
    path('show/', include(app.urls))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'account.views.err404'
# handler500 = 'account.views.500'
# handler403 = 'account.views.403'
# handler400 = 'account.views.400'

app/templates/app/create.html
{% extends 'base.html' %}
{% load static %}

{% block extracss %}
  <link rel="stylesheet" href="{% static 'css/createcss.css' %}">
  <title>Create</title>
{% endblock %}

{% block header %}
      {%include 'components/header.html' %}
{% endblock %}

{% block body %}
<div class="page page1">
        <div class="page1-text">
            <div class="mainHead">
                <h2>Create new project.</h2>
            </div>
            <p>Enter all fields and upload files for better viewing experience .</p>

            <div class="stacked-inputs" style="width:100%;">
              {% if error %}
              <div class="error-mask" style="width:100%">
                <p>{{error}}</p>
              </div>
              {% endif %}

                <form method="POST" action="{% url 'app:create' %}" enctype="multipart/form-data">
                  {% csrf_token %}
                    <div class="row">

                        <div class="col-lg-6 col-md-6 col-sm-12">

                            <input type="text"  name="projname" placeholder="Project Name">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">
                            <input type="file"  placeholder="Icon " name="myfile" id="myfile"/>
                        </div>

                    </div>
                    <div class="row">

                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <input style="width:100%;" type="text"  name="desc" placeholder="App Description">
                        </div>

                    </div>
                    <div class="row">

                        <div class="col-lg-6 col-md-6 col-sm-12">

                            <input type="text" name="gitlink"  placeholder="Github link ( if any )">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">

                            <input type="text" name="playlink"   placeholder="PlayStore link ( if any )">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">

                            <input type="text" name="appstorelink"  placeholder="AppStore link ( if any )">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">

                            <input type="text"  name="weblink" placeholder="Web link ( if any )">
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-12">

                            <input type="text"  name="vidlink" placeholder="Video link ( if any )">
                        </div>

                    </div>
                    <input type="submit" type="button" class="prevbutton" value="Create">
                </form>

            </div>


        </div>

    </div>

{% endblock %}


{% block javascript %}
<script type="text/javascript">

</script>
{% endblock %}